### ISSUE TITLE
Missing Next button after entering Project nam

### ISSUE THREAD

**Issue by sonnemaf** [jpobst/classic-dotnet-templates#3]
Hi,

I love your solution. But after installing the NuGet package I don't get a `Next` button in this dialog, only `Create`. So I can't check the checkboxes.

![image](https://user-images.githubusercontent.com/9335559/140073369-56fb5a57-21ce-43ce-ab25-3bf3bfdbcefe.png)

Is this a Visual Studio 2022 bug? I had the same problem with @dotMorten solution (https://github.com/dotnet/templating/issues/3985) but suddenly the Next button came back. Trying your and @dotMorten solution on an other computer also went wrong. Both didn't have the `Next` button. '

Any Idea how to fix it? I can imagine that is hard to solve due to the fact that you might not be able to reproduce it. Maybe more users have this issue and maybe one of them knows a solution.

**Comment by jpobst** [comment]
Hmm, it doesn't seem to work for me either on the latest preview (Version 17.0.0 Preview 7.0).  Maybe Microsoft decided it made them look bad?  😉

**Comment by sonnemaf** [comment]
OK, I will close the issue then. Thanks.

**Comment by jpobst** [comment]
It looks like this is working again in VS2022 Final.  🎉

**Comment by sonnemaf** [comment]
I can confirm this. It **doesn't** work in VS2022 Preview (Version 17.1.0 Preview 1.0). Wondering why?
